### ISSUE TITLE
Search for everything in the same loop

### ISSUE THREAD

**Issue by Mino260806** [NeonOrbit/Dexplore#2]
This is a critical performance improvement, this library is only efficient when looking for just one method. However, finding many methods and classes causes to loop through the same classes for every single search. Why not search for everything in the same loop?

### Example
**old code**
```
Class<?> class1 = dexplore.findClass(
                DEX_FILTER,
                CLASS_FILTER).loadClass(classLoader)

Class<?> class2 = dexplore.findClass(
                DEX_FILTER,
                CLASS_FILTER).loadClass(classLoader)
```

**new code**
```
dexplore.addClass("class1",
                DEX_FILTER,
                CLASS_FILTER)
dexplore.addClass("class2",
                DEX_FILTER,
                CLASS_FILTER)

dexplore.setClassLoader(classLoader)
dexplore.setOnClassQueried((name, cls) -> { 
    switch(name) {
        case "class1":
            class1 = cls;
            break;
        case "class2":
            class2 = cls;
            break;
    }
})

dexplore.explore()
```

**Comment by NeonOrbit** [comment]
You can add mutiple classes (or conditions) to the same ClassFilter.
`CLASS_FILTER.setClasses(cA, cB, ...);`

For more explicit query, create some basic filters and use:
`dexplore.onClassResults();`
`dexplore.onMethodResults();`
..

I'm sorry, I was busy. I'll release a new versions with these changes (including documentations). Just needs a final review before publishing it.

**Comment by Mino260806** [comment]
Sorry, I wasn't very clear with my suggestion. It does work when using the same ClassFilter in order to get multiple results. What I want to do is to find different classes with different class filters but traverse the dex files one time. Referencing back my example with a slight change

```
dexplore.addClass("class1",
                DEX_FILTER,
                CLASS_FILTER_1) // different
dexplore.addClass("class2",
                DEX_FILTER,
                CLASS_FILTER_2) // different

dexplore.setClassLoader(classLoader)
dexplore.setOnClassQueried((name, cls) -> { 
    switch(name) {
        case "class1":
            class1 = cls;
            break;
        case "class2":
            class2 = cls;
            break;
    }
})

dexplore.explore()
```

Is this possible with the current implementation ?

**Comment by NeonOrbit** [comment]
Well, I did think about it but there was a drawback (I don't remember). I did some performance tests once, it doesn't really cost much. Once the dex files are loaded into the memory, traversing them are almost instant. If you are searching for a lot of classes, you need to show a loading dialog anyway. Also if your ClassFilter has multiple conditions (specially checking references), then traversing through a dex file is almost negligible. 
Nevertheless, I'll test again to see what was the drawback. BTW, what did you mean by "class1", "class2"? are these actual class names or some arbitrary strings to identify your query uniquely?

About `setClassLoader(classLoader)` method:
`loadClass()` is there for convenience only. You should use Xposed API to load classes, which has an internal caching mechanism. 
Or you can use lambda `classResults.map(c -> c.loadClass(classloader)).toList();`

**Comment by Mino260806** [comment]
Thanks for considering my suggestion. And yes, "class1" and "class2" are some arbitrary strings to identify the query later on

**Comment by Mino260806** [comment]
I think it does hit performance, just copy paste the same findClass command 10 times or so and you'll notice a remarkable loading time

**Comment by NeonOrbit** [comment]
I'll get right on it

**Comment by NeonOrbit** [comment]
> I think it does hit performance, just copy paste the same findClass command 10 times or so and you'll notice a remarkable loading time

I did some performance tests. The loading time that you are getting here is not for traversing through the dex classes, it's for verifying the filters again (which is necessary).

Actually, traversing through classes from a dex file doesn't load them immediately, every single field of a class object loads directly from a shared byte buffer. Which means even if we search for two items in the same loop, we are still verifying/accessing the same fields both times from the same buffer. In case of separate loops, the only overhead is recreating the DexClass objects, which is super fast (I couldn't get it to pass 1 ms limit, with thousands of classes). However decoding references takes time, that's why there is an option called `enabledCache` in `DexOptions`, if your dexfilter has ReferenceFilter condition, you should enable this option. 

Still I was considering a single loop implementation, but seems it's not worth the trouble. 
I'll have to keep track of queries that matched (DexFilter) against a dex file, so that I can apply the selected queries (ClassFilter) on each class, which means accessing a map for every single class (much worse than separate loops). And if it's a method query, well, new map for each class in a dex.

**Comment by NeonOrbit** [comment]
@Mino260806 I was testing the library to see if it needs any adjustments, figured out almost all the obfuscated classes used in messenger pro. Let me know if you need it.

**Comment by Mino260806** [comment]
@NeonOrbit thanks I'd appreciate your help

**Comment by NeonOrbit** [comment]
[MProFetcher.zip](https://github.com/NeonOrbit/Dexplore/files/9120108/MProFetcher.zip)

**Comment by Mino260806** [comment]
> [MProFetcher.zip](https://github.com/NeonOrbit/Dexplore/files/9120108/MProFetcher.zip)

@NeonOrbit Im impressed about the massive work you have done. It should've taken you so much time. Thank you very much

**Comment by NeonOrbit** [comment]
NP.

**Comment by NeonOrbit** [comment]
ab24001...4a03db0
